// constants.tsx
export const API_BASE_URL = "http://localhost:4000/api/wms/write";

export const STORAGE_KEYS = {
  DEVICE_TOKEN: "ASSTRO_DEVICE_TOKEN",
  WMS_TYPE: "ASSTRO_WMS_TYPE",
  REGION_ID: "ASSTRO_REGION_ID",
  BRANCH_ID: "ASSTRO_BRANCH_ID",
  ACTIVE_OPERATOR: "WMS_ACTIVE_OPERATOR",
  CACHE_KATALOG: "WMS_CACHE_KATALOG",
  MASTER_STAFF: "WMS_MASTER_STAFF",
} as const;
